Labapp/urls.py
from os import name
from django.urls import path
from django.conf import settings
from . import views

app_name = 'Labapp'
urlpatterns = [ 
    path('', views.index, name='index'),
    path('Index/', views.Index, name='Index'),
    path('register/', views.register, name='register'),
    path('registration/', views.registration, name='registration'),
    path('homepage/', views.homepage, name='homepage'),
    path('software/', views.software, name='software'),
    path('softwaredata/', views.softwaredata, name='softwaredata'),
    path('hardware/', views.hardware, name='hardware'),
    path('hardwaredata/', views.hardwaredata, name='hardwaredata'),
    path('equipmentdevice/', views.equipmentdevice, name='equipmentdevice'),
    path('EquipmentDevice/', views.EquipmentDevice, name='EquipmentDevice'),
    path('performrequest/', views.performrequest, name='performrequest'),
    path('update/<int:id>', views.update, name='update'),
    path('records/', views.records, name='records'),
    path('emails/', views.emails, name='emails'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('logout/', views.logoutUser, name='logout'),


    
]

Ourproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('Labapp.urls')),

    path('admin/', admin.site.urls),
]

Labapp/models.py
from pickle import TRUE
from sqlite3 import Date
from django.db import models
import os
from django.db.models.deletion import CASCADE
import django.utils.timezone

from django.contrib.auth.models import AbstractUser

class register1(AbstractUser):
    job_option = [
        ('Computer Instructor', 'Computer Instructor'),
        ('UITC Staff', 'UITC Staff'),
    ]
    Job_description = models.CharField(max_length = 40, null=False, choices=job_option)
    id = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')



class index(models.Model):
    id = models.ForeignKey(register1,unique=True, on_delete= CASCADE, primary_key= True,)
    User_name = models.CharField(max_length= 50, null=False)
    Password_data =models.CharField(default= "", max_length =40, null=False, unique = True)


    


class homepage(models.Model):

    Availability = [
        ('AVAILABLE ', 'AVAILABLE '),
        ('OCCUPIED ', 'OCCUPIED '),

        ]
    Section_name= models.CharField(max_length= 50, null=False)
    date = models.DateField( default=django.utils.timezone.now, )
    Time_in = models.TimeField(null=False)
    Time_out = models.TimeField(null=False)
    Status = models.CharField(max_length=50, choices = Availability, null=False)


    
    
    

class hardware_reports(models.Model):
    Laboratories = [
        ('LABORATORY 1', 'LABORATORY 1'),
        ('LABORATORY 2', 'LABORATORY 2'),
        ('LABORATORY 3', 'LABORATORY 3'),
        ('LABORATORY 4', 'LABORATORY 4'),
        ]
    name = models.CharField(max_length=100, null = False)
    Lab_num = models.CharField(max_length=50, choices = Laboratories, null=False)
    Pc_num = models.IntegerField(null=False)
    System_unit = models.CharField(max_length=10, null=True)
    Monitor = models.CharField(max_length=10, null=True)
    keyboard = models.CharField(max_length=10, null=True)
    Mouse = models.CharField(max_length=10, null=True)
    Avr = models.CharField(max_length=10, null=True)
    Comments = models.CharField(max_length=50)

    

class software_reports(models.Model):
    Laboratory_num = [
        ('LABORATORY 1', 'LABORATORY 1'),
        ('LABORATORY 2', 'LABORATORY 2'),
        ('LABORATORY 3', 'LABORATORY 3'),
        ('LABORATORY 4', 'LABORATORY 4'),
        ]
    Concern = [
        ('Request', 'Request'),
        ('Complain', 'Complain'),
        ('Suggest', 'Suggest'),
        ('Others', 'Others'),
        ]
    User_name = models.CharField(max_length=100, null=False)
    Lab_num = models.CharField(max_length=50, choices = Laboratory_num, null=False)
    Pc_num = models.IntegerField(null=False)
    Type_concern = models.CharField(max_length=50, choices = Concern, null=False)
    Message = models.CharField(max_length=256, null=False)

    

class equipmentdevicel1(models.Model):
    lab_num = models.PositiveIntegerField(primary_key=True, null=False)
    pc_num =models.PositiveIntegerField()
    system_unit = models.CharField(max_length=10, null=True)
    monitor = models.CharField(max_length=10, null=True)
    keyboard = models.CharField(max_length=10, null=True)
    mouse = models.CharField(max_length=10, null=True)
    avr = models.CharField(max_length=10, null=True)
    r_choices = [
        ('Good', 'Good'),
        ('Replace', 'Replace'),
        ('On-process', 'Onprocess'),
        ]
    remarks = models.CharField(max_length=20, choices=r_choices)


class perform_request(models.Model):
    date = models.DateField(default=django.utils.timezone.now)
    name = models.CharField(max_length=100)
    Lab_num = models.CharField(max_length=50)
    Pc_num = models.PositiveIntegerField()
    Type_report = models.CharField(max_length=100)
    remarks = models.CharField(max_length=300)
    s_choices = [
        ('Ongoing', 'Ongoing'),
        ('Available to use', 'Available to use'),
    ]
    status = models.CharField(max_length=30, choices= s_choices)

Labapp/forms.py
from tkinter import Widget
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import register1



class StaffRegistration(UserCreationForm):
    class Meta:
        model= register1
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'Job_description']
       
        
class instructorRegistration(UserCreationForm):
    class Meta:
        model = register1
        fields = ['username','first_name','last_name', 'email', 'password1', 'password2', 'Job_description']


        

Labapp/views.py
from multiprocessing import context
from django.contrib.messages.api import MessageFailure
from django.forms.widgets import EmailInput
from django.shortcuts import render, redirect
from .models import *
from django.contrib.auth.models import User, auth
from django.contrib.auth import authenticate
from .forms import StaffRegistration, instructorRegistration
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.mail import message, send_mail
from django.core.mail import EmailMessage
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import smtplib

installed_apps = ['Labapp']




def registration(request):
    form = instructorRegistration()
    if request.method == "POST":
        form = instructorRegistration(request.POST)
        if form.is_valid():


            form.save()
            messages.success(request, 'You are now registered')
            name = request.POST['first_name'] + " " + request.POST['last_name']
            emails = request.POST['email']
            message = "You are succesfully registered as " + request.POST['Job_description'] + "! \n Your Username is " + request.POST['username'] + '.'


            email = EmailMessage(
                name,
                message,
                'lab.mon.tupc@gmail.com',
                [emails],

                )

            email.send()

            return redirect('/Index')
        else:
            messages.warning(request, "Recheck all your input info")
    context = {
        'form':form
    }


    return render(request, 'pages/REGISTER.html', context)


def index(request):
    if request.method == 'POST':
        username = request.POST.get('email')
        password = request.POST.get('password')

        user = authenticate(request, username = username, password = password)
        if user is not None and user.Job_description == "Computer Instructor":
            login(request, user)
            return redirect('/homepage')

        elif user is not None and user.Job_description == "UITC Staff":
            login(request, user)
            return redirect('/EquipmentDevice')
        else:
            messages.warning(request, 'Invalid Credentials')

    elif request.user.is_authenticated and request.user.Job_description == "UITC Staff":
        return redirect('/EquipmentDevice')
    elif request.user.is_authenticated and request.user.Job_description == "Computer Instructor":
        return redirect('/homepage')

    return render(request, 'pages/LOG.html')


def Index(request):
    return redirect('/')


@login_required(login_url='/Index')
def logoutUser(request):
    logout(request)
    request.user.Job_description = None
    return redirect('/Index')


def register(request):
   return render(request, 'pages/REGISTER.html')

@login_required(login_url='/Index')
def homepage(request):
    if request.user.is_authenticated and request.user.Job_description == 'Computer Instructor':
        return render(request, 'pages/HOMEPAGE.html')
    elif request.user.is_authenticated and request.user.Job_description == 'UITC Staff':
        return redirect('/EquipmentDevice')
    else:
        return redirect('/Index')

@login_required(login_url='/Index')
def hardware(request):
    if request.user.is_authenticated and request.user.Job_description == 'Computer Instructor':
        return render(request, 'pages/HARDWARE.html')
    elif request.user.is_authenticated and request.user.Job_description == 'UITC Staff':
        return redirect('/EquipmentDevice')
    else:
        return redirect('/Index')

@login_required(login_url='/Index')
def software(request):
    if request.user.is_authenticated and request.user.Job_description == 'Computer Instructor':
        return render(request, 'pages/SOFTWARE.html')
    elif request.user.is_authenticated and request.user.Job_description == 'UITC Staff':
        return redirect('/EquipmentDevice')
    else:
        return redirect('/Index')

@login_required(login_url='/Index')
def EquipmentDevice(request):
    if request.user.is_authenticated and request.user.Job_description == 'UITC Staff':
        return render(request, 'pages/EQUIPMENT_DEVICE.html')
    elif request.user.is_authenticated and request.user.Job_description == 'Computer Instructor':
        return redirect('/homepage')
    else:
        return redirect('/Index')

def update(request, id):
    a = perform_request.objects.get(id=id)

    for x in perform_request.objects.only('id').filter(status= "Ongoing"):


        if a == x:
            x = perform_request.objects.filter(id=id).update(status="Available")
            break
    messages.success(request, "Successfully done")
    return redirect('/performrequest')

def delete(request, id):
    a = perform_request.objects.get(id=id)
    for x in perform_request.objects.only('id').filter(status= "Ongoing"):

        print(x)
        if a == x:
            d = "a"
            print(d)
            x = perform_request.objects.get(id=id).delete()
            break
    messages.info(request, "Successfully deleted")
    return redirect('/performrequest')



@login_required(login_url='/Index')
def performrequest(request):
    if request.user.is_authenticated and request.user.Job_description == 'UITC Staff':
        data = perform_request.objects.filter(status = "Ongoing")
        return render(request, 'pages/PERFORM_REQUEST.html',{'data':data})
    elif request.user.is_authenticated and request.user.Job_description == 'Computer Instructor':
        return redirect('/homepage')
    else:
        return redirect('/Index')

def emails(request):
    if request.method=='POST':
        name = "Queries"
        emailss = request.POST['emails']
        messages = request.POST['messages']
        email = EmailMessage(
            name,
            messages,
            'lab.mon.tupc@gmail.com',
            [emailss],

            )

        email.send()

        return redirect('/homepage')


@login_required(login_url='/Index')
def records(request):
    if request.user.is_authenticated and request.user.Job_description == 'UITC Staff':
        data = perform_request.objects.all()

        return render(request, 'pages/RECORDS.html',{'data':data})
    elif request.user.is_authenticated and request.user.Job_description == 'Computer Instructor':
        return redirect('/homepage')
    else:
        return redirect('/Index')

def equipmentdevice(request):
    if request.method=='POST':
        Labnum = request.POST.get('lab1')
        pcnum = "1"
        sysunit = request.POST.get('system_unit')
        mntr = request.POST.get('monitor')
        kbrd = request.POST.get('kboard')
        ms = request.POST.get('mouse')
        Avr = request.POST.get('avr')
        Remarks = request.POST.get('rmrks')
        data = equipmentdevicel1.objects.create(lab_num = Labnum, pc_num=pcnum, system_unit=sysunit, monitor=mntr, keyboard=kbrd, mouse=ms, avr=Avr, remarks=Remarks)
        data.save()
        return redirect("/EquipmentDevice")

def softwaredata(request):
    if request.method=='POST':
        Uname = request.POST.get('Username')
        Labno = request.POST.get('Labnum')
        Pcno = request.POST.get('Pcnum')
        TypeofC = request.POST.get('TypeofConcern')
        Mess = request.POST.get('Message')
        status = 'Ongoing'
        data = software_reports.objects.create(User_name=Uname, Lab_num=Labno, Pc_num=Pcno, Type_concern=TypeofC, Message=Mess)
        data1 = perform_request.objects.create(name=Uname, Lab_num=Labno, Pc_num=Pcno, Type_report=TypeofC, remarks=Mess, status = status)
        data1.save()
        data.save()
        messages.success(request, "Software Report submitted")
        return redirect('/software')

def hardwaredata(request):

    if request.method=='POST':
        name = request.POST.get('name')
        labnum = request.POST.get('labnum')
        pcno = request.POST.get('pcnum')
        s_unit = request.POST.get('sys_unit')
        mtr = request.POST.get('mntor')
        kbrd = request.POST.get('kboard')
        ms = request.POST.get('mouse')
        avr = request.POST.get('AVR')
        cmmt = request.POST.get('comment')
        status = 'Ongoing'
        data = hardware_reports.objects.create(name=name, Lab_num=labnum, Pc_num=pcno, System_unit=s_unit, Monitor=mtr, keyboard=kbrd, Mouse=ms, Avr=avr, Comments=cmmt )
        data1 = perform_request.objects.create(name=name, Lab_num=labnum, Pc_num=pcno, Type_report=s_unit, remarks=cmmt, status = status)
        data1.save()
        data.save()
        messages.success(request, "Hardware Report submitted")
        return redirect('/hardware')

Labapp/templates/pages/HARDWARE.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UITC Laboratory Monitoring</title>
    <link rel="icon" href="{% static 'Media/TUPLOGO.png' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'CSS/hardware.css' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    
   <!-----fonts-->
   <link rel="preconnect" href="https://fonts.googleapis.com">
   <link rel="preconnect" href="https://fonts.googleapis.com">
   <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
   <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,400;0,500;1,300&display=swap" rel="stylesheet">
    <script src="{% static 'JS/hrdwr.js' %}"></script>
</head>
<body>
  
  
  <div class="menu-bar">
    <nav class="navbar navbar-expand-lg navbar-dark stic">
        <a class="navbar-brand" href="#"><img src="{% static 'Media/TUPLOGO.png' %}">UITC LABORATORY </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#greennavbar" aria-controls="greennavbar" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

      
        <div class="collapse navbar-collapse" id="greennavbar">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link van" href="{% url 'Labapp:homepage' %}">Home Page </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle van active" href="#" id="dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Reports
                </a>
                <div class="dropdown-menu">
                  <a class="dropdown-item active" href="#">Hardware<span class="sr-only">(current)</span> </a>
                  <a class="dropdown-item " href="{% url 'Labapp:software' %}">Software</a>
                </div>
            </li>

            <li>
              <a class="nav-link van" href="#" data-toggle="modal" data-target="#mod">Help</a>
            </li>
            
          <li class="nav-item">
              <a class="nav-link van" href="{% url 'Labapp:logout' %}">Logout</a>
            </li>
             
          </ul>
          
        </div>
    </nav>


    <div class="modal fade" id="mod" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" id="dal">
          <div class="modal-header">
            <h5 class="modal-title" id="MODAL1">What to do in Hardware Reports??</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            ...
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
            
          </div>
        </div>
      </div>
    </div>
    



        
    <div class="modal fade" id="dom" tabindex="-1" role="dialog" aria-labelledby="domTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h6 class="modal-title" id="MODAL2">Notification</h6>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Do you really want to submit this report?
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal" id="c2">Cancel</button>
            <button type="submit" class="btn btn-primary" data-dismiss="modal" id="y2">Yes</button>
          </div>
        </div>
      </div>
    </div>


    <div class="modal fade" id="add" tabindex="-1" role="dialog" aria-labelledby="adds" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" id="dal">
          <div class="modal-header">
            <h6 class="modal-title" id="MODAL2">Notification</h6>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <input id="n1" type="number" min="0" max="20" placeholder="Add Row"></input>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal" id="c1">Cancel</button>
            <button type="button" class="btn btn-primary" data-dismiss="modal" id="y1">Yes</button>
          </div>
        </div>
      </div>
    </div>
    


  </div>  
  
  <div class="color-overlay"> </div>
  <div id="pic" class="view drk ">
    <div class="color-overlay"> </div>
    <div class="container text-center"><br><br>
      <div class="jumbotron " ><br>
          {%for message in messages%}
            {% if message.tags == 'success'%}
              <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
              <script>
                  var m = "{{message}}";
                  swal("Congrats", m, "success")
              </script>
            {% endif %}
          {%endfor%}
          <div class="card-header">
            Hardware Report
          </div>
          <div class="card-body">
            <div class="card-title">
              <form method='post' action = '/hardwaredata/'>
                {%csrf_token%}
                <div class="form-row">
                  <div class="col-5 p-1">
                    <input type="text" class="form-control" placeholder="Input Name" id="name" name="name" required>
                  </div>
                </div> 
            </div>
            <div>
              <div class="container"  >
                <div class="table-responsive" id="table1" >
                    <table class="table" id="tbl_lab1">
                        <thead scope="row" class="thead">
                            <tr>
                              <th scope="col">Lab no.</th>
                              <th scope="col">PC no.</th>
                              <th scope="col">System Unit</th>
                              <th scope="col">Monitor</th>
                              <th scope="col">Keyboard</th>
                              <th scope="col">Mouse</th>
                              <th scope="col">AVR</th>
                              <th scope="col">Comments</th>
              
                            </tr>
                          </thead>
              
                          <tbody class="table-dark" id="tb1">
                            <tr id="row_data">
                              <td> 
                                <select class="form-control form-control-sm" id="labl" name="labnum">
                                  <option>Lab 1</option>
                                  <option>Lab 2</option>
                                  <option>Lab 3</option>
                                  <option>Lab 4</option>
                                </select>
                              </td>
                              <td> 
                                  <input type="number" min="1" max="50" class="form-control" placeholder="PC#" id="PCnum" name="pcnum" required>
                              </td>
                              <td> <input type="checkbox" name="sys_unit"></td>
                              <td> <input type="checkbox"name="mntor"></td>
                              <td> <input type="checkbox"name="kboard"></td>
                              <td> <input type="checkbox" name="mouse"></td>
                              <td> <input type="checkbox" name="AVR"></td>
                              <td> <input type="text" class="form-control" placeholder="Comment" id="com" name="comment" required></td>
                            </tr>
                        </tbody>
                      </table>  
              
                </div>
              </div>
            </div>
            
            <p class="card-text">Check it properly before you live it.</p>
  
            
   <!------------------------------------------------------------------------------------SECOND MODAL BUTTONS PART----------------------------------------------------------------------------------------------------------->
            <!--id nito dati submit-->
            <button type="button" onclick="submit()" class="btn btn-primary hah" id="B1" disabled>
              Submit Report
            </button>
            <button type="button" class="btn btn-danger hah" id="B2" onclick="cancel1()">
              Cancel
            </button>
          </form>
          </div>
        
      </div>
    

    
  </div>


</body>
</html>

Labapp/templates/pages/PERFORM_REQUEST.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UITC Laboratory Monitoring</title>
    <link rel="icon" href="{% static 'Media/TUP LOGO.png' %}">
    <link rel="stylesheet"  href="{% static 'CSS/perform_request.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'JS/performreq.js' %}"></script>
  </head>
<body>

  <div class="menu-bar">
    <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand" href="#"><img src="{% static 'Media/TUP LOGO.png' %}">UITC LABORATORY </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item ">
              <a class="nav-link van" href="{% url 'Labapp:EquipmentDevice' %}">Equipment Device</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="#">
                  Perform Request
                  <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link van" href="{% url 'Labapp:records' %}">
                  Records
                </a>
            </li>
            <li class="nav-item">
              <a class="nav-link van" href="{% url 'Labapp:logout' %}">Logout</a>
            </li>
          </ul>
          
        </div>
    </nav>
  
  </div>
  <form>
  <div class="color-overlay"></div>
  <div id="pic" class="view drk ">
    <div class="color-overlay"></div>
      <div class="jumbotron" >
        
        {%for message in messages%}
            {% if message.tags == 'info'%}
            <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
            <script>
                var m = "{{message}}";
                swal("Delete", m, "success")
            </script>
            {% endif %}
            {% if message.tags == 'success'%}
            <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
            <script>
                var m = "{{message}}";
                swal("Congrats", m, "success")
            </script>
            {% endif %}
        {%endfor%}
        <div class="container text-center"><br><br>
          <div class="table-responsive">
            <div class="card-header">
              <h2 id="pangalan">REPORTS</h2> <br></br>
            </div>
            <div class="card-body">
              <form>
                
                <table class="table table-striped" id="tbl_report">
                  <thead class="thead">
                    <tr>
                      <th scope="col">Name</th>
                      <th scope="col">Lab No.</th>
                      <th scope="col">PC No.</th>
                      <th scope="col">Type of Report</th>
                      <th scope="col">Remarks</th>
                      <th scope="col">Status</th>


                    </tr>
                  </thead>
                  <tbody class="table-color">
                    <tr id="row_data" >
                      {% for report in data %}
                      <td>{{report.name}}</td>
                      <td>{{report.Lab_num}}</td>
                      <td>{{report.Pc_num}}</td>
                      <td>{{report.Type_report}}</td>
                      <td>{{report.remarks}}</td>
                      <td>
                        <a class="btn btn-sm" type='button' id = 'Save' href="{% url 'Labapp:update' report.pk  %}" > Done </a>    <a class="btn btn-sm" type='button' id = 'Save' href="{% url 'Labapp:delete' report.pk %}" > Delete </a>
                      </td>                
                    </tr>
                      {% endfor%}
                  </tbody>
                  
                  
                  <tfoot>

                  </tfoot>
                  
                </table>
              </form>
            </div>
          </div>
        </div>
      </div>



  </div>
    
  </form>  
  
  


</body>
</html>